### ISSUE TITLE
[RFE] enhance with ouctl for Open Unison

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/devcontainer#3]
# Problem

Add ouctl for openunison on Kargo https://github.com/ContainerCraft/Kargo/issues/6

**Comment by usrbinkat** [comment]
Blocked on multi-arch ouctl support.

**Comment by mlbiam** [comment]
hot off the presses - https://nexus.tremolo.io/repository/ouctl/ouctl-0.0.12-macos-arm64.zip

bit of a silly question - I've got a YAML that I publish for krew as a plugin (this is a "manual plugin").  Is there a specific format that I should publish the version as?  Does it need just the version or latest URLs or ...?

**Comment by mlbiam** [comment]
ok, so i'm thinking.  The `ouctl` command is just a wrapper for helm.  It creates a `Secret`, deploys some helm charts, and makes sure they finish before moving on to the next one.  i can do all that with pulumi natively, right?  Looking at your cert_manager code.  I should be able to write a pulumi script that:

1. Generates a values.yaml based on some variables
2. Generate a secret
3. run a bunch of helm charts in sequence, not starting the next chart until the previous one is complete

right?

**Comment by usrbinkat** [comment]
@mlbiam yes, we can just write the helm and k8s resources in pulumi and skip the ouctl dependency entirely. Sounds good.

**Comment by mlbiam** [comment]
Kewl. Was looking at the code for cert manager and I should be able to get this working pretty easily.

**Comment by usrbinkat** [comment]
@mlbiam I'll close this issue on Konductor then in favor of https://github.com/ContainerCraft/Kargo/issues/6
